#docker-compose.yaml
version: "3.1"
services:
  mysql:
    image: mysql:5.6
    container_name: ${PROJECT_NAME}-mysql
    working_dir: /application
    volumes:
      - db-data:/application
      # - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=docker_root
      - MYSQL_DATABASE=ngcommx
      - MYSQL_USER=ngcommx_user
      - MYSQL_PASSWORD=ngcommx_pw
    ports:
      - "8306:3306"
    networks:
      - ngcommx-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: docker_root
    ports:
      - "8001:80"
    links:
      # for mysql container
      - "mysql:mysql"
    networks:
      - ngcommx-net

  webserver:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - php-fpm
    networks:
      - ngcommx-net

  php-fpm:
    build: docker/php-fpm/
    container_name: ${PROJECT_NAME}-php-fpm
    working_dir: /application
    environment:
      - APP_ENV=docker
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    networks:
      - ngcommx-net

volumes:
  db-data:

networks:
  ngcommx-net: